### ISSUE TITLE
Suggestion: Replace the !IsDebuggerPresent() loop with a MessageBox

### ISSUE THREAD

**Issue by igromanru** [gottyduke/SF_PluginTemplate#6]
Currently the `!IsDebuggerPresent()` loop in the Debug build will freeze the process until you attach a debugger. If you start the game by accident with your debug build or simply don't need a debugger to test something, you're forced to attach a debugger, no way around.  
```cpp
#ifndef NDEBUG
	while (!IsDebuggerPresent()) {
		Sleep(100);
	}
#endif
```
What I like to use instead, is a MessageBox. The MessageBox will "freeze" the process in place as well, but you can simply click on **OK** to continue or attach a debugger first.
```cpp
#ifndef NDEBUG
    MessageBoxA(NULL, "Loaded. You can attach the debugger now", "Plugin Name", NULL);
#endif
```  

Just wanted to share the idea.

**Comment by gottyduke** [comment]
Good call,thank you for the addition!
